os: linux
dist: trusty

language: shell

branches:
  only:
    - master
    - develop

before_script:
  - env | sort
  - export TAG=travis
  - export VCS_REF=`git rev-parse --short HEAD`
  - export BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
  - export IMAGE_NAME=letsvote

script:
  # Build project
  - cp env.dist .env
  - docker-compose up -d
  - docker-compose exec phpfpm /app/bin/console doctrine:schema:create
  # Execute project Unit Tests
  - docker-compose exec phpfpm /app/bin/phpunit -c /app/phpunit.xml.dist
  # Run project
  - echo "[TODO] Test that your project runs properly"

notifications:
  email: false

matrix:
  allow_failures:
    - env: VERSION=0.1
  
env: # Environments
    - VERSION=1.0
